name: CI Pipeline

on: push

jobs:
  project-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install dvc

      - name: Run DVC pipeline
        env:
          DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }} 
        run: |
          dvc repro

      - name: Run model tests
        env:
          DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
        run: |
          python -m unittest tests/test_model.py

      - name: Promote model to production
        if: success()
        env:
          DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
        run: |
          python scripts/promote_model.py

      - name: Run Flask app tests
        if: success()
        env:
          DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
        run: |
          python -m unittest tests/test_flask_app.py

      - name: Log in to Azure Container Registry (ACR)
        run: |
          az acr login --name emotionacr --username ${{ secrets.AZURE_USERNAME }} --password ${{ secrets.AZURE_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t shivamshankaraacharya/emotion1 .

      - name: Tag Docker image
        run: |
          docker tag shivamshankaraacharya/emotion1:latest emotionacr.azurecr.io/shivamshankaraacharya/emotion1:latest

      - name: Push Docker image to Azure Container Registry (ACR)
        run: |
          docker push emotionacr.azurecr.io/shivamshankaraacharya/emotion1:latest

      - name: Deploy to Azure Container Instance (ACI)
        run: |
          az container create --resource-group NetworkWatcherRG \
            --name emotionaci \
            --image emotionacr.azurecr.io/shivamshankaraacharyaemotion1:latest \
            --cpu 1 \
            --memory 1 \
            --ports 80 \
            --environment-variables DAGSHUB_PAT=${{ secrets.DAGSHUB_PAT }}

      - name: Verify Deployment
        run: |
          az container show --resource-group NetworkWatcherRG \
            --name emotionaci \  # Changed to match the container name used in the deployment step.
            --query "{IP:ipAddress.ip, ProvisioningState:provisioningState}" --out table  # Corrected the query format

